import Head from "next/head";

export function CustomHead(props) {
  return (
    // Com a propriedade Head importada do proprio next/head podemos configurar o head da nossa pagina
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700;800&display=optional" rel="stylesheet" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}